version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264351046.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t product-service .
      - echo "Tagging the image.."
      - docker tag product-service:latest 058264351046.dkr.ecr.us-east-1.amazonaws.com/product-service:latest

      
  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push 058264351046.dkr.ecr.us-east-1.amazonaws.com/product-service:latest
      
      
artifacts:
  files: 
     - '**/*'
